coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

component_management:
  individual_components:
    - component_id: ui-craft
      paths:
        - packages/ui-craft/
      statuses:
        - type: project
          target: auto
    - component_id: color-contrast-cli
      paths:
        - packages/color-contrast-cli/
      statuses:
        - type: project
          target: auto

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
